package shared.base

/**
 * Generic base for all backend items.
 */
interface GenericItem {
    /**
     * The id of the item, if there is one. This is usually generated by the backend.
     */
    val id: Int?

    /**
     * The date that the item was created. This is usually automatically generated by the backend.
     */
    val dateCreated: Long

    /**
     * The date that the item was updated last. This is usually automatically generated by the backend.
     */
    val dateUpdated: Long
}
